server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/jiagou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    password: 123456